articles/urls.py
from django.urls import path

from .views import (
    article_search_view,
    article_create_view,
    article_details_view
)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),  
    path('create/', article_create_view, name='create'),  
    path('<slug:slug>/', article_details_view, name='detail'),
]

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_update_view
)

app_name = 'recipes' # recipes:list, recipes:create

urlpatterns = [
    path('', recipe_list_view, name='list'),
    path('create/', recipe_create_view, name='create'),  
    path('<int:id>/edit/', recipe_update_view, name='update'),
    path('<int:id>/', recipe_detail_view, name='detail'),
]

trydjango/urls.py
# CTRL + SHIFT P and then "Developer: reload window" if app does not visible here in import

from django.contrib import admin
from django.urls import include, path

from accounts.views import (
    login_view, 
    logout_view,
    register_view,
)

from articles.views import (
    article_search_view,
    article_create_view,
    article_details_view
)
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/base.html
<!DOCTYPE html>
<html>
    <head>

    </head>
     <body>

         <form action="/articles/" method="GET">
            <input type="text" name="q">
            <input type="submit">
         </form>

         {% block content %}
         {% endblock content %}
     </body>
</html>

templates/home-view.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}} - {{id}}</h1>

<p>{{content}}</p>

<a href='{% url "articles:create" %}'>Create Article</a>

<p>{{article_list}}</p>
<ul>
{% for x in article_list %}
    {% if x.title %}
        <li><a href="{{ x.get_absolute_url }}">{{x.title}} - {{x.content }}</a></li>
    {% endif %}
{% endfor %}
<ul>

{% endblock content %}